USE book_club_web_data;

INSERT INTO scraped(title,category,stars,price,is_in_stock) VALUES
("Sharp Objects","Mystery","4","47.82","Yes"),
("In a Dark, Dark Wood","Mystery","1","19.63","Yes"),
("The Past Never Ends","Mystery","4","56.50","Yes"),
("A Murder in Time","Mystery","1","16.64","Yes"),
("The Murder of Roger Ackroyd (Hercule Poirot #4)","Mystery","4","44.10","Yes"),
("The Last Mile (Amos Decker #2)","Mystery","2","54.21","Yes"),
("That Darkness (Gardiner and Renner #1)","Mystery","1","13.92","Yes"),
("Tastes Like Fear (DI Marnie Rome #3)","Mystery","1","10.69","Yes"),
("A Time of Torment (Charlie Parker #14)","Mystery","5","48.35","Yes"),
("A Study in Scarlet (Sherlock Holmes #1)","Mystery","2","16.73","Yes"),
("Poisonous (Max Revere Novels #3)","Mystery","3","26.80","Yes"),
("Murder at the 42nd Street Library (Raymond Ambler #1)","Mystery","4","54.36","Yes"),
("Most Wanted","Mystery","3","35.28","Yes"),
("Hide Away (Eve Duncan #20)","Mystery","1","11.84","Yes"),
("Boar Island (Anna Pigeon #19)","Mystery","3","59.48","Yes"),
("The Widow","Mystery","2","27.26","Yes"),
("Playing with Fire","Mystery","3","13.71","Yes"),
("What Happened on Beale Street (Secrets of the South Mysteries #2)","Mystery","5","25.37","Yes"),
("The Bachelor Girl's Guide to Murder (Herringford and Watts Mysteries #1)","Mystery","5","52.30","Yes"),
("Delivering the Truth (Quaker Midwife Mystery #1)","Mystery","4","20.89","Yes"),
("It's Only the Himalayas","Travel","2","45.17","Yes"),
("Full Moon over Noahâ's Ark: An Odyssey to Mount Ararat and Beyond","Travel","4","49.43","Yes"),
("See America: A Celebration of Our National Parks & Treasured Sites","Travel","3","48.87","Yes"),
("Vagabonding: An Uncommon Guide to the Art of Long-Term World Travel","Travel","2","36.94","Yes"),
("Under the Tuscan Sun","Travel","3","37.33","Yes"),
("A Summer In Europe","Travel","2","44.34","Yes"),
("The Great Railway Bazaar","Travel","1","30.54","Yes"),
("A Year in Provence (Provence #1)","Travel","4","56.88","Yes"),
("The Road to Little Dribbling: Adventures of an American in Britain (Notes From a Small Island #2)","Travel","1","23.21","Yes"),
("Neither Here nor There: Travels in Europe","Travel","3","38.95","Yes"),
("1,000 Places to See Before You Die","Travel","5","26.08","Yes"),
("The Mysterious Affair at Styles (Hercule Poirot #1)","Mystery","4","24.80","Yes"),
("In the Woods (Dublin Murder Squad #1)","Mystery","2","38.38","Yes"),
("The Silkworm (Cormoran Strike #2)","Mystery","5","23.05","Yes"),
("The Exiled","Mystery","3","43.45","Yes"),
("The Cuckoo's Calling (Cormoran Strike #1)","Mystery","1","19.21","Yes"),
("Extreme Prey (Lucas Davenport #26)","Mystery","3","25.40","Yes"),
("Career of Evil (Cormoran Strike #3)","Mystery","2","24.72","Yes"),
("The No. 1 Ladies' Detective Agency (No. 1 Ladies' Detective Agency #1)","Mystery","4","57.70","Yes"),
("The Girl You Lost","Mystery","5","12.29","Yes"),
("The Girl In The Ice (DCI Erika Foster #1)","Mystery","3","15.85","Yes"),
("Blood Defense (Samantha Brinkman #1)","Mystery","3","20.30","Yes"),
("1st to Die (Women's Murder Club #1)","Mystery","1","53.98","Yes"),
("Tipping the Velvet","Historical Fiction","1","53.74","Yes"),
("Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton","Historical Fiction","3","29.69","Yes"),
("A Flight of Arrows (The Pathfinders #2)","Historical Fiction","5","55.53","Yes"),
("The House by the Lake","Historical Fiction","1","36.95","Yes"),
("Mrs. Houdini","Historical Fiction","5","30.25","Yes"),
("The Marriage of Opposites","Historical Fiction","4","28.08","Yes"),
("Glory over Everything: Beyond The Kitchen House","Historical Fiction","3","45.84","Yes"),
("Love, Lies and Spies","Historical Fiction","2","20.55","Yes"),
("A Paris Apartment","Historical Fiction","4","39.01","Yes"),
("Lilac Girls","Historical Fiction","2","17.28","Yes"),
("The Constant Princess (The Tudor Court #1)","Historical Fiction","3","16.62","Yes"),
("The Invention of Wings","Historical Fiction","1","37.34","Yes"),
("World Without End (The Pillars of the Earth #2)","Historical Fiction","4","32.97","Yes"),
("The Passion of Dolssa","Historical Fiction","5","28.32","Yes"),
("Girl With a Pearl Earring","Historical Fiction","1","26.77","Yes"),
("Voyager (Outlander #3)","Historical Fiction","5","21.07","Yes"),
("The Red Tent","Historical Fiction","5","35.66","Yes"),
("The Last Painting of Sara de Vos","Historical Fiction","2","55.55","Yes"),
("The Guernsey Literary and Potato Peel Pie Society","Historical Fiction","1","49.53","Yes"),
("Girl in the Blue Coat","Historical Fiction","2","46.83","Yes"),
("Between Shades of Gray","Historical Fiction","5","20.79","Yes"),
("While You Were Mine","Historical Fiction","5","41.32","Yes"),
("The Secret Healer","Historical Fiction","3","34.56","Yes"),
("Starlark","Historical Fiction","3","25.83","Yes"),
("Lost Among the Living","Historical Fiction","4","27.70","Yes"),
("A Spy's Devotion (The Regency Spies of London #1)","Historical Fiction","5","16.97","Yes"),
("Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)","Sequential Art","5","52.29","Yes"),
("Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)","Sequential Art","1","16.28","Yes"),
("This One Summer","Sequential Art","4","19.49","Yes"),
("The Nameless City (The Nameless City #1)","Sequential Art","4","38.16","Yes"),
("Saga, Volume 5 (Saga (Collected Editions) #5)","Sequential Art","2","51.04","Yes"),
("Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)","Sequential Art","3","50.40","Yes"),
("Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)","Sequential Art","5","13.61","Yes"),
("Pop Gun War, Volume 1: Gift","Sequential Art","1","18.97","Yes"),
("Patience","Sequential Art","3","10.16","Yes"),
("Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)","Sequential Art","4","15.44","Yes"),
("orange: The Complete Collection 1 (orange: The Complete Collection #1)","Sequential Art","1","48.41","Yes"),
("Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)","Sequential Art","2","46.91","Yes"),
("Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)","Sequential Art","3","45.61","Yes"),
("Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)","Sequential Art","2","19.92","Yes"),
("I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)","Sequential Art","2","29.17","Yes"),
("I am a Hero Omnibus Volume 1","Sequential Art","3","54.63","Yes"),
("Giant Days, Vol. 2 (Giant Days #5-8)","Sequential Art","2","22.11","Yes"),
("Danganronpa Volume 1","Sequential Art","4","51.99","Yes"),
("Codename Baboushka, Volume 1: The Conclave of Death","Sequential Art","4","36.72","Yes"),
("Camp Midnight","Sequential Art","4","17.08","Yes"),
("Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))","Sequential Art","2","37.92","Yes"),
("The Shadow Hero (The Shadow Hero)","Sequential Art","1","33.14","Yes"),
("Fables, Vol. 1: Legends in Exile (Fables #1)","Sequential Art","4","41.62","Yes"),
("Batman: The Long Halloween (Batman)","Sequential Art","2","36.50","Yes"),
("Batman: The Dark Knight Returns (Batman)","Sequential Art","5","15.38","Yes"),
("Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)","Sequential Art","4","37.34","Yes"),
("We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)","Sequential Art","1","53.90","Yes"),
("Through the Woods","Sequential Art","2","25.38","Yes"),
("Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)","Sequential Art","5","11.89","Yes"),
("So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)","Sequential Art","4","35.43","Yes"),
("Robin War","Sequential Art","3","47.82","Yes"),
("Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)","Sequential Art","2","25.48","Yes"),
("Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)","Sequential Art","2","38.39","Yes"),
("Lowriders to the Center of the Earth (Lowriders in Space #2)","Sequential Art","2","51.51","Yes"),
("El Deafo","Sequential Art","5","57.62","Yes"),
("Batman: Europa","Sequential Art","2","32.01","Yes"),
("Art Ops Vol. 1","Sequential Art","3","48.80","Yes"),
("Adulthood Is a Myth: A 'Sarah's Scribbles' Collection","Sequential Art","2","10.90","Yes"),
("Fruits Basket, Vol. 9 (Fruits Basket #9)","Sequential Art","4","33.95","Yes"),
("Roller Girl","Sequential Art","5","14.10","Yes"),
("Fruits Basket, Vol. 7 (Fruits Basket #7)","Sequential Art","1","19.57","Yes"),
("Fruits Basket, Vol. 6 (Fruits Basket #6)","Sequential Art","4","20.96","Yes"),
("Death Note, Vol. 6: Give-and-Take (Death Note #6)","Sequential Art","3","36.39","Yes"),
("Fruits Basket, Vol. 5 (Fruits Basket #5)","Sequential Art","1","16.33","Yes"),
("Death Note, Vol. 5: Whiteout (Death Note #5)","Sequential Art","1","52.41","Yes"),
("The Demon Prince of Momochi House, Vol. 4 (The Demon Prince of Momochi House #4)","Sequential Art","2","27.88","Yes"),
("Fruits Basket, Vol. 4 (Fruits Basket #4)","Sequential Art","4","50.44","Yes"),
("The Wicked + The Divine, Vol. 3: Commercial Suicide (The Wicked + The Divine)","Sequential Art","3","14.41","Yes"),
("The Sandman, Vol. 3: Dream Country (The Sandman (volumes) #3)","Sequential Art","5","55.55","Yes"),
("Saga, Volume 3 (Saga (Collected Editions) #3)","Sequential Art","5","21.57","Yes"),
("Prodigy: The Graphic Novel (Legend: The Graphic Novel #2)","Sequential Art","3","43.63","Yes"),
("Persepolis: The Story of a Childhood (Persepolis #1-2)","Sequential Art","1","39.13","Yes"),
("Original Fake","Sequential Art","3","31.45","Yes"),
("Grayson, Vol 3: Nemesis (Grayson #3)","Sequential Art","1","42.72","Yes"),
("Fruits Basket, Vol. 3 (Fruits Basket #3)","Sequential Art","2","45.17","Yes"),
("Black Butler, Vol. 1 (Black Butler #1)","Sequential Art","1","49.31","Yes"),
("Awkward","Sequential Art","2","38.02","Yes"),
("The Sandman, Vol. 2: The Doll's House (The Sandman (volumes) #2)","Sequential Art","1","54.81","Yes"),
("Saga, Volume 2 (Saga (Collected Editions) #2)","Sequential Art","3","11.75","Yes"),
("Fruits Basket, Vol. 2 (Fruits Basket #2)","Sequential Art","5","11.64","Yes"),
("The Secret Garden","Classics","4","15.08","Yes"),
("The Metamorphosis","Classics","1","28.58","Yes"),
("The Pilgrim's Progress","Classics","2","50.26","Yes"),
("The Hound of the Baskervilles (Sherlock Holmes #5)","Classics","2","14.82","Yes"),
("Little Women (Little Women #1)","Classics","4","28.07","Yes"),
("Gone with the Wind","Classics","3","32.49","Yes"),
("Candide","Classics","3","58.63","Yes"),
("Animal Farm","Classics","3","57.22","Yes"),
("Wuthering Heights","Classics","3","17.73","Yes"),
("The Picture of Dorian Gray","Classics","2","29.70","Yes"),
("The Complete Stories and Poems (The Works of Edgar Allan Poe [Cameo Edition])","Classics","4","26.78","Yes"),
("Beowulf","Classics","2","38.35","Yes"),
("And Then There Were None","Classics","2","35.01","Yes"),
("The Story of Hong Gildong","Classics","4","43.19","Yes"),
("The Little Prince","Classics","2","45.42","Yes"),
("Sense and Sensibility","Classics","1","37.46","Yes"),
("Of Mice and Men","Classics","2","47.11","Yes"),
("Emma","Classics","2","32.93","Yes"),
("Alice in Wonderland (Alice's Adventures in Wonderland #1)","Classics","1","55.53","Yes"),
("Y: The Last Man, Vol. 1: Unmanned (Y: The Last Man #1)","Sequential Art","4","18.51","Yes"),
("The Wicked + The Divine, Vol. 1: The Faust Act (The Wicked + The Divine)","Sequential Art","2","36.52","Yes"),
("The Sandman, Vol. 1: Preludes and Nocturnes (The Sandman (volumes) #1)","Sequential Art","3","54.12","Yes"),
("The Complete Maus (Maus #1-2)","Sequential Art","3","10.64","Yes"),
("Skip Beat!, Vol. 01 (Skip Beat! #1)","Sequential Art","3","42.12","Yes"),
("Saga, Volume 1 (Saga (Collected Editions) #1)","Sequential Art","1","28.48","Yes"),
("Rat Queens, Vol. 1: Sass & Sorcery (Rat Queens (Collected Editions) #1-5)","Sequential Art","5","46.96","Yes"),
("Paper Girls, Vol. 1 (Paper Girls #1-5)","Sequential Art","4","21.71","Yes"),
("Ouran High School Host Club, Vol. 1 (Ouran High School Host Club #1)","Sequential Art","3","29.87","Yes"),
("Ms. Marvel, Vol. 1: No Normal (Ms. Marvel (2014-2015) #1)","Sequential Art","4","39.39","Yes"),
("Hawkeye, Vol. 1: My Life as a Weapon (Hawkeye #1)","Sequential Art","3","45.24","Yes"),
("Giant Days, Vol. 1 (Giant Days #1-4)","Sequential Art","4","56.76","Yes"),
("Fruits Basket, Vol. 1 (Fruits Basket #1)","Sequential Art","5","40.28","Yes"),
("Bleach, Vol. 1: Strawberry and the Soul Reapers (Bleach #1)","Sequential Art","5","34.65","Yes"),
("Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)","Sequential Art","4","57.06","Yes"),
("Sophie's World","Philosophy","5","15.94","Yes"),
("The Death of Humanity: and the Case for Life","Philosophy","4","58.11","Yes"),
("The Stranger","Philosophy","4","17.44","Yes"),
("Proofs of God: Classical Arguments from Tertullian to Barth","Philosophy","1","54.21","Yes"),
("Kierkegaard: A Christian Missionary to Christians","Philosophy","1","47.13","Yes"),
("At The Existentialist CafÃ©: Freedom, Being, and apricot cocktails with: Jean-Paul Sartre, Simone de Beauvoir, Albert Camus, Martin Heidegger, Edmund Husserl, Karl Jaspers, Maurice Merleau-Ponty and others","Philosophy","5","29.93","Yes"),
("Critique of Pure Reason","Philosophy","1","20.75","Yes"),
("Run, Spot, Run: The Ethics of Keeping Pets","Philosophy","1","20.02","Yes"),
("The Nicomachean Ethics","Philosophy","1","36.34","Yes"),
("Meditations","Philosophy","2","25.89","Yes"),
("Beyond Good and Evil","Philosophy","1","43.38","Yes"),
("Chase Me (Paris Nights #2)","Romance","5","25.27","Yes"),
("Black Dust","Romance","5","34.53","Yes"),
("Her Backup Boyfriend (The Sorensen Family #1)","Romance","1","33.97","Yes"),
("First and First (Five Boroughs #3)","Romance","4","15.97","Yes"),
("Fifty Shades Darker (Fifty Shades #2)","Romance","1","21.96","Yes"),
("The Wedding Dress","Romance","1","24.12","Yes"),
("Suddenly in Love (Lake Haven #1)","Romance","2","55.99","Yes"),
("Something More Than This","Romance","4","16.24","Yes"),
("Doing It Over (Most Likely To #1)","Romance","3","35.61","Yes"),
("The Wedding Pact (The O'Malleys #2)","Romance","3","32.61","Yes"),
("Hold Your Breath (Search and Rescue #1)","Romance","1","28.82","Yes"),
("Dirty (Dive Bar #1)","Romance","4","40.83","Yes"),
("Take Me Home Tonight (Rock Star Romance #3)","Romance","3","53.98","Yes"),
("Off the Hook (Fishing for Trouble #1)","Romance","3","47.67","Yes"),
("A Gentleman's Position (Society of Gentlemen #3)","Romance","5","14.75","Yes"),
("Sit, Stay, Love","Romance","3","20.90","Yes"),
("A Girl's Guide to Moving On (New Beginnings #2)","Romance","1","31.30","Yes"),
("The Perfect Play (Play by Play #1)","Romance","3","59.99","Yes"),
("Dark Lover (Black Dagger Brotherhood #1)","Romance","1","12.87","Yes"),
("Changing the Game (Play by Play #2)","Romance","3","13.38","Yes"),
("A Walk to Remember","Romance","1","56.43","Yes"),
("The Purest Hook (Second Circle Tattoos #3)","Romance","1","12.25","Yes"),
("The Obsession","Romance","1","45.43","Yes"),
("Reservations for Two","Romance","3","11.10","Yes"),
("Best of My Love (Fool's Gold #20)","Romance","2","27.41","Yes"),
("Where Lightning Strikes (Bleeding Stars #3)","Romance","3","39.77","Yes"),
("This One Moment (Pushing Limits #1)","Romance","1","48.71","Yes"),
("Rhythm, Chord & Malykhin","Romance","2","28.34","Yes"),
("My Perfect Mistake (Over the Top #1)","Romance","2","38.92","Yes"),
("Listen to Me (Fusion #1)","Romance","3","58.99","Yes"),
("Imperfect Harmony","Romance","4","34.74","Yes"),
("Fighting Fate (Fighting #6)","Romance","3","39.24","Yes"),
("Deep Under (Walker Security #1)","Romance","5","47.09","Yes"),
("Charity's Cross (Charles Towne Belles #4)","Romance","1","41.24","Yes"),
("Bounty (Colorado Mountain #7)","Romance","4","37.26","Yes"),
("I Had a Nice Time And Other Lies...: How to find love & sh*t like that","Womens Fiction","4","57.36","Yes"),
("Will You Won't You Want Me?","Womens Fiction","3","13.86","Yes"),
("Keep Me Posted","Womens Fiction","4","20.46","Yes"),
("Grey (Fifty Shades #4)","Womens Fiction","4","48.49","Yes"),
("Meternity","Womens Fiction","3","43.58","Yes"),
("Some Women","Womens Fiction","5","13.73","Yes"),
("Shopaholic Ties the Knot (Shopaholic #3)","Womens Fiction","5","48.39","Yes"),
("Can You Keep a Secret?","Womens Fiction","1","21.94","Yes"),
("Twenties Girl","Womens Fiction","2","42.80","Yes"),
("The Undomestic Goddess","Womens Fiction","4","45.75","Yes"),
("The Nanny Diaries (Nanny #1)","Womens Fiction","5","52.53","Yes"),
("The Devil Wears Prada (The Devil Wears Prada #1)","Womens Fiction","1","44.29","Yes"),
("Something Borrowed (Darcy & Rachel #1)","Womens Fiction","5","48.96","Yes"),
("Something Blue (Darcy & Rachel #2)","Womens Fiction","1","54.62","Yes"),
("I've Got Your Number","Womens Fiction","1","19.69","Yes"),
("The Edge of Reason (Bridget Jones #2)","Womens Fiction","4","19.18","Yes"),
("Bridget Jones's Diary (Bridget Jones #1)","Womens Fiction","1","29.82","Yes"),
("Soumission","Fiction","1","50.10","Yes"),
("Private Paris (Private #10)","Fiction","5","47.61","Yes"),
("We Love You, Charlie Freeman","Fiction","5","50.27","Yes"),
("Thirst","Fiction","5","17.27","Yes"),
("The Murder That Never Was (Forensic Instincts #5)","Fiction","3","54.11","Yes"),
("Tuesday Nights in 1980","Fiction","2","21.04","Yes"),
("The Vacationers","Fiction","4","42.15","Yes"),
("The Regional Office Is Under Attack!","Fiction","5","51.36","Yes"),
("Finders Keepers (Bill Hodges Trilogy #2)","Fiction","5","53.53","Yes"),
("The Time Keeper","Fiction","5","27.88","Yes"),
("The Testament of Mary","Fiction","4","52.67","Yes"),
("The First Hostage (J.B. Collins #2)","Fiction","3","25.85","Yes"),
("Take Me with You","Fiction","3","45.21","Yes"),
("Still Life with Bread Crumbs","Fiction","3","26.41","Yes"),
("Shtum","Fiction","4","55.84","Yes"),
("My Name Is Lucy Barton","Fiction","1","41.56","Yes"),
("My Mrs. Brown","Fiction","3","24.48","Yes"),
("Mr. Mercedes (Bill Hodges Trilogy #1)","Fiction","1","28.90","Yes"),
("I Am Pilgrim (Pilgrim #1)","Fiction","4","10.60","Yes"),
("Eligible (The Austen Project #4)","Fiction","3","27.09","Yes"),
("Eight Hundred Grapes","Fiction","4","14.39","Yes"),
("Dear Mr. Knightley","Fiction","5","11.21","Yes"),
("Cometh the Hour (The Clifton Chronicles #6)","Fiction","3","25.01","Yes"),
("Balloon Animals","Fiction","3","17.03","Yes"),
("A Man Called Ove","Fiction","1","39.72","Yes"),
("The Silent Sister (Riley MacPherson #1)","Fiction","5","46.29","Yes"),
("The Dinner Party","Fiction","2","56.54","Yes"),
("The Improbability of Love","Fiction","1","59.45","Yes"),
("Mothering Sunday","Fiction","2","13.34","Yes"),
("Lies and Other Acts of Love","Fiction","1","45.14","Yes"),
("Daredevils","Fiction","3","16.34","Yes"),
("11/22/63","Fiction","3","48.48","Yes"),
("The Shack","Fiction","1","28.03","Yes"),
("The High Mountains of Portugal","Fiction","1","51.15","Yes"),
("Miller's Valley","Fiction","2","58.54","Yes"),
("Hystopia: A Novel","Fiction","4","21.96","Yes"),
("The Bourne Identity (Jason Bourne #1)","Fiction","4","42.78","Yes"),
("Sister Dear","Fiction","4","40.20","Yes"),
("Memoirs of a Geisha","Fiction","3","49.67","Yes"),
("Me Before You (Me Before You #1)","Fiction","1","19.02","Yes"),
("Deception Point","Fiction","4","40.32","Yes"),
("The Little Paris Bookshop","Fiction","3","24.73","Yes"),
("The Firm","Fiction","3","45.56","Yes"),
("The Expatriates","Fiction","2","44.58","Yes"),
("Siddhartha","Fiction","5","34.22","Yes"),
("Last One Home (New Beginnings #1)","Fiction","3","59.98","Yes"),
("Digital Fortress","Fiction","5","58.00","Yes"),
("Atlas Shrugged","Fiction","5","26.58","Yes"),
("Three-Martini Lunch","Fiction","3","23.21","Yes"),
("The Nightingale","Fiction","4","26.26","Yes"),
("The Infinities","Fiction","1","27.41","Yes"),
("The Husband's Secret","Fiction","5","52.51","Yes"),
("The Da Vinci Code (Robert Langdon #2)","Fiction","2","22.96","Yes"),
("The Art of Fielding","Fiction","1","22.10","Yes"),
("Lila (Gilead #3)","Fiction","3","12.47","Yes"),
("Jurassic Park (Jurassic Park #1)","Fiction","1","44.97","Yes"),
("Inferno (Robert Langdon #4)","Fiction","5","41.00","Yes"),
("Crazy Rich Asians (Crazy Rich Asians #1)","Fiction","5","49.13","Yes"),
("Big Little Lies","Fiction","1","22.11","Yes"),
("The Course of Love","Fiction","3","16.78","Yes"),
("When I'm Gone","Fiction","3","51.96","Yes"),
("The Silent Wife","Fiction","5","12.34","Yes"),
("The Bette Davis Club","Fiction","3","30.66","Yes"),
("Kitchens of the Great Midwest","Fiction","5","57.20","Yes"),
("Bright Lines","Fiction","5","39.07","Yes"),
("Birdsong: A Story in Pictures","Childrens","3","54.64","Yes"),
("The Bear and the Piano","Childrens","1","36.89","Yes"),
("The Secret of Dreadwillow Carse","Childrens","1","56.13","Yes"),
("The White Cat and the Monk: A Retelling of the Poem âPangur BÃ¡nâ","Childrens","4","58.08","Yes"),
("Little Red","Childrens","3","13.47","Yes"),
("Walt Disney's Alice in Wonderland","Childrens","5","12.96","Yes"),
("Twenty Yawns","Childrens","2","22.08","Yes"),
("Rain Fish","Childrens","3","23.57","Yes"),
("Once Was a Time","Childrens","2","18.28","Yes"),
("Luis Paints the World","Childrens","3","53.95","Yes"),
("Nap-a-Roo","Childrens","1","25.08","Yes"),
("The Whale","Childrens","4","35.96","Yes"),
("Shrunken Treasures: Literary Classics, Short, Sweet, and Silly","Childrens","3","52.87","Yes"),
("Raymie Nightingale","Childrens","2","34.41","Yes"),
("Playing from the Heart","Childrens","1","32.38","Yes"),
("Maybe Something Beautiful: How Art Transformed a Neighborhood","Childrens","1","22.54","Yes"),
("The Wild Robot","Childrens","3","56.07","Yes"),
("The Thing About Jellyfish","Childrens","1","48.77","Yes"),
("The Lonely Ones","Childrens","5","43.59","Yes"),
("The Day the Crayons Came Home (Crayons)","Childrens","5","26.33","Yes"),
("The Cat in the Hat (Beginner Books B-1)","Childrens","2","16.26","Yes"),
("Red: The True Story of Red Riding Hood","Childrens","3","28.54","Yes"),
("Horrible Bear!","Childrens","2","37.52","Yes"),
("Green Eggs and Ham (Beginner Books B-16)","Childrens","4","10.79","Yes"),
("Counting Thyme","Childrens","1","10.62","Yes"),
("Are We There Yet?","Childrens","3","10.66","Yes"),
("Diary of a Minecraft Zombie Book 1: A Scare of a Dare (An Unofficial Minecraft Book)","Childrens","4","52.88","Yes"),
("Matilda","Childrens","1","28.34","Yes"),
("Charlie and the Chocolate Factory (Charlie Bucket #1)","Childrens","3","22.85","Yes"),
("Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master","Religion","2","37.97","Yes"),
("You Are What You Love: The Spiritual Power of Habit","Religion","4","21.87","Yes"),
("God: The Most Unpleasant Character in All Fiction","Religion","5","30.03","Yes"),
("The Book of Mormon","Religion","3","24.57","Yes"),
("A History of God: The 4,000-Year Quest of Judaism, Christianity, and Islam","Religion","1","27.62","Yes"),
("The Bhagavad Gita","Religion","3","57.49","Yes"),
("Choosing Our Religion: The Spiritual Lives of America's Nones","Religion","4","28.42","Yes"),
("Worlds Elsewhere: Journeys Around Shakespeareâ's Globe","Nonfiction","5","40.30","Yes"),
("The Five Love Languages: How to Express Heartfelt Commitment to Your Mate","Nonfiction","3","31.05","Yes"),
("Reasons to Stay Alive","Nonfiction","2","26.41","Yes"),
("#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.","Nonfiction","5","23.11","Yes"),
("Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness","Nonfiction","4","44.18","Yes"),
("Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity","Nonfiction","3","31.12","Yes"),
("The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing","Nonfiction","3","16.77","Yes"),
("The Gutsy Girl: Escapades for Your Life of Epic Adventure","Nonfiction","1","37.13","Yes"),
("The Electric Pencil: Drawings from Inside State Hospital No. 3","Nonfiction","1","56.06","Yes"),
("Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up","Nonfiction","4","41.83","Yes"),
("Reskilling America: Learning to Labor in the Twenty-First Century","Nonfiction","2","19.83","Yes"),
("In the Country We Love: My Family Divided","Nonfiction","4","22.00","Yes"),
("Everydata: The Misinformation Hidden in the Little Data You Consume Every Day","Nonfiction","2","54.35","Yes"),
("Call the Nurse: True Stories of a Country Nurse on a Scottish Isle","Nonfiction","5","29.14","Yes"),
("Algorithms to Live By: The Computer Science of Human Decisions","Nonfiction","1","30.81","Yes"),
("The Power of Now: A Guide to Spiritual Enlightenment","Nonfiction","2","43.54","Yes"),
("The Omnivore's Dilemma: A Natural History of Four Meals","Nonfiction","2","38.21","Yes"),
("The Genius of Birds","Nonfiction","1","17.24","Yes"),
("The Artist's Way: A Spiritual Path to Higher Creativity","Nonfiction","5","38.49","Yes"),
("So You've Been Publicly Shamed","Nonfiction","2","12.23","Yes"),
("Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead","Nonfiction","3","19.43","Yes"),
("Big Magic: Creative Living Beyond Fear","Nonfiction","3","30.80","Yes"),
("Becoming Wise: An Inquiry into the Mystery and Art of Living","Nonfiction","2","27.43","Yes"),
("Agnostic: A Spirited Manifesto","Nonfiction","5","12.51","Yes"),
("Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity","Nonfiction","4","38.20","Yes"),
("What's It Like in Space?: Stories from Astronauts Who've Been There","Nonfiction","2","19.60","Yes"),
("The Year of Magical Thinking","Nonfiction","2","43.04","Yes"),
("The Literature Book (Big Ideas Simply Explained)","Nonfiction","3","17.43","Yes"),
("The Bad-Ass Librarians of Timbuktu: And Their Race to Save the Worldâ's Most Precious Manuscripts","Nonfiction","1","15.77","Yes"),
("Swell: A Year of Waves","Nonfiction","1","45.58","Yes"),
("No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon","Nonfiction","2","21.95","Yes"),
("Looking for Lovely: Collecting the Moments that Matter","Nonfiction","5","29.14","Yes"),
("Let It Out: A Journey Through Journaling","Nonfiction","5","26.79","Yes"),
("Hamilton: The Revolution","Nonfiction","3","58.79","Yes"),
("Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years","Nonfiction","4","15.06","Yes"),
("Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life","Nonfiction","5","51.75","Yes"),
("Buying In: The Secret Dialogue Between What We Buy and Who We Are","Nonfiction","4","37.80","Yes"),
("Brain on Fire: My Month of Madness","Nonfiction","5","49.32","Yes"),
("Abstract City","Nonfiction","5","56.37","Yes"),
("13 Hours: The Inside Account of What Really Happened In Benghazi","Nonfiction","1","27.06","Yes"),
("The Lonely City: Adventures in the Art of Being Alone","Nonfiction","2","33.26","Yes"),
("The Diary of a Young Girl","Nonfiction","3","59.90","Yes"),
("Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas","Nonfiction","3","21.21","Yes"),
("Furiously Happy: A Funny Book About Horrible Things","Nonfiction","4","41.46","Yes"),
("The Sleep Revolution: Transforming Your Life, One Night at a Time","Nonfiction","4","11.68","Yes"),
("Mother, Can You Not?","Nonfiction","5","16.89","Yes"),
("A Mother's Reckoning: Living in the Aftermath of Tragedy","Nonfiction","3","19.53","Yes"),
("10% Happier: How I Tamed the Voice in My Head, Reduced Stress Without Losing My Edge, and Found Self-Help That Actually Works","Nonfiction","2","24.57","Yes"),
("Chernobyl 01:23:40: The Incredible True Story of the World's Worst Nuclear Disaster","Nonfiction","2","35.92","Yes"),
("Zero to One: Notes on Startups, or How to Build the Future","Nonfiction","3","34.06","Yes"),
("Why Not Me?","Nonfiction","1","17.76","Yes"),
("When Breath Becomes Air","Nonfiction","2","39.36","Yes"),
("The Midnight Assassin: Panic, Scandal, and the Hunt for America's First Serial Killer","Nonfiction","4","28.45","Yes"),
("Smarter Faster Better: The Secrets of Being Productive in Life and Business","Nonfiction","5","38.89","Yes"),
("Rising Strong","Nonfiction","3","21.82","Yes"),
("Man's Search for Meaning","Nonfiction","3","29.48","Yes"),
("Love That Boy: What Two Presidents, Eight Road Trips, and My Son Taught Me About a Parent's Expectations","Nonfiction","2","25.06","Yes"),
("Living Forward: A Proven Plan to Stop Drifting and Get the Life You Want","Nonfiction","3","12.55","Yes"),
("I Will Find You","Nonfiction","1","44.21","Yes"),
("Brazen: The Courage to Find the You That's Been Hiding","Nonfiction","2","19.22","Yes"),
("Between the World and Me","Nonfiction","4","56.91","Yes"),
("Being Mortal: Medicine and What Matters in the End","Nonfiction","4","55.06","Yes"),
("A Murder Over a Girl: Justice, Gender, Junior High","Nonfiction","3","13.20","Yes"),
("For the Love: Fighting for Grace in a World of Impossible Standards","Nonfiction","3","45.13","Yes"),
("Finding God in the Ruins: How God Redeems Pain","Nonfiction","2","46.64","Yes"),
("The Man Who Mistook His Wife for a Hat and Other Clinical Tales","Nonfiction","4","59.45","Yes"),
("In Cold Blood","Nonfiction","4","49.98","Yes"),
("Girl, Interrupted","Nonfiction","3","42.14","Yes"),
("Why Save the Bankers?: And Other Essays on Our Economic and Political Crisis","Nonfiction","2","48.67","Yes"),
("Talking to Girls About Duran Duran: One Young Man's Quest for True Love and a Cooler Haircut","Nonfiction","4","25.15","Yes"),
("My Mother Was Nuts","Nonfiction","4","31.63","Yes"),
("Data, A Love Story: How I Gamed Online Dating to Meet My Match","Nonfiction","3","32.35","Yes"),
("The Jazz of Physics: The Secret Link Between Music and the Structure of the Universe","Nonfiction","3","38.71","Yes"),
("The Gunning of America: Business and the Making of American Gun Culture","Nonfiction","4","16.81","Yes"),
("The Geography of Bliss: One Grump's Search for the Happiest Places in the World","Nonfiction","2","28.23","Yes"),
("God Is Not Great: How Religion Poisons Everything","Nonfiction","1","27.80","Yes"),
("We the People: The Modern-Day Figures Who Have Reshaped and Affirmed the Founding Fathers' Vision of America","Nonfiction","3","31.95","Yes"),
("Very Good Lives: The Fringe Benefits of Failure and the Importance of Imagination","Nonfiction","3","50.66","Yes"),
("Unstuffed: Decluttering Your Home, Mind, and Soul","Nonfiction","1","58.09","Yes"),
("Under the Banner of Heaven: A Story of Violent Faith","Nonfiction","1","30.00","Yes"),
("Trespassing Across America: One Man's Epic, Never-Done-Before (and Sort of Illegal) Hike Across the Heartland","Nonfiction","1","53.51","Yes"),
("The Name of God is Mercy","Nonfiction","2","37.25","Yes"),
("Stiff: The Curious Lives of Human Cadavers","Nonfiction","3","36.74","Yes"),
("Spilled Milk: Based on a True Story","Nonfiction","1","49.51","Yes"),
("Rise of the Rocket Girls: The Women Who Propelled Us, from Missiles to the Moon to Mars","Nonfiction","4","41.67","Yes"),
("Outliers: The Story of Success","Nonfiction","1","14.16","Yes"),
("Notes from a Small Island (Notes From a Small Island #1)","Nonfiction","1","40.17","Yes"),
("Night (The Night Trilogy #1)","Nonfiction","1","13.51","Yes"),
("Miracles from Heaven: A Little Girl, Her Journey to Heaven, and Her Amazing Story of Healing","Nonfiction","1","57.83","Yes"),
("Letter to a Christian Nation","Nonfiction","1","22.20","Yes"),
("Let's Pretend This Never Happened: A Mostly True Memoir","Nonfiction","1","45.11","Yes"),
("It's Never Too Late to Begin Again: Discovering Creativity and Meaning at Midlife and Beyond","Nonfiction","1","42.38","Yes"),
("Into the Wild","Nonfiction","5","56.70","Yes"),
("In the Garden of Beasts: Love, Terror, and an American Family in Hitler's Berlin","Nonfiction","3","28.85","Yes"),
("I Am Malala: The Girl Who Stood Up for Education and Was Shot by the Taliban","Nonfiction","2","28.88","Yes"),
("Gratitude","Nonfiction","5","26.66","Yes"),
("Disrupted: My Misadventure in the Start-Up Bubble","Nonfiction","5","15.28","Yes"),
("Brave Enough","Nonfiction","5","51.32","Yes"),
("Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen","Nonfiction","2","27.35","Yes"),
("Blink: The Power of Thinking Without Thinking","Nonfiction","5","21.74","Yes"),
("Black Flags: The Rise of ISIS","Nonfiction","1","40.87","Yes"),
("Are We Smart Enough to Know How Smart Animals Are?","Nonfiction","1","56.58","Yes"),
("A Walk in the Woods: Rediscovering America on the Appalachian Trail","Nonfiction","4","30.48","Yes"),
("The Suffragettes (Little Black Classics, #96)","Nonfiction","2","11.89","Yes"),
("Kindle Paperwhite User's Guide","Nonfiction","3","34.00","Yes"),
("H is for Hawk","Nonfiction","5","57.42","Yes"),
("Travels with Charley: In Search of America","Nonfiction","5","57.82","Yes"),
("The Tumor","Nonfiction","5","41.56","Yes"),
("The End of the Jesus Era (An Investigation #1)","Nonfiction","1","14.40","Yes"),
("Eat, Pray, Love","Nonfiction","3","51.32","Yes"),
("Rip it Up and Start Again","Music","5","35.02","Yes"),
("Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991","Music","3","57.25","Yes"),
("How Music Works","Music","2","37.32","Yes"),
("Love Is a Mix Tape (Music #1)","Music","1","18.03","Yes"),
("Please Kill Me: The Uncensored Oral History of Punk","Music","4","31.19","Yes"),
("Kill 'Em and Leave: Searching for James Brown and the American Soul","Music","5","45.05","Yes"),
("Chronicles, Vol. 1","Music","2","52.60","Yes"),
("This Is Your Brain on Music: The Science of a Human Obsession","Music","1","38.40","Yes"),
("Orchestra of Exiles: The Story of Bronislaw Huberman, the Israel Philharmonic, and the One Thousand Jews He Saved from Nazi Horrors","Music","3","12.36","Yes"),
("No One Here Gets Out Alive","Music","5","20.02","Yes"),
("Life","Music","5","31.58","Yes"),
("Old Records Never Die: One Man's Quest for His Vinyl and His Past","Music","2","55.66","Yes"),
("Forever Rockers (The Rocker #12)","Music","3","28.80","Yes"),
("The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull","Default","3","17.93","Yes"),
("The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics","Default","4","22.60","Yes"),
("Starving Hearts (Triangular Trade Trilogy, #1)","Default","2","13.99","Yes"),
("America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana","Default","3","22.50","Yes"),
("Aladdin and His Wonderful Lamp","Default","3","53.13","Yes"),
("Penny Maybe","Default","3","33.29","Yes"),
("Maude (1883-1993):She Grew Up with the country","Default","2","18.02","Yes"),
("The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer","Default","5","20.59","Yes"),
("Soul Reader","Default","2","39.58","Yes"),
("Bossypants","Default","2","49.46","Yes"),
("A World of Flavor: Your Gluten Free Passport","Default","1","42.95","Yes"),
("A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations","Default","5","56.76","Yes"),
("Tracing Numbers on a Train","Default","3","41.60","Yes"),
("Thirteen Reasons Why","Default","1","52.72","Yes"),
("The Secret (The Secret #1)","Default","4","27.37","Yes"),
("The Psychopath Test: A Journey Through the Madness Industry","Default","2","36.00","Yes"),
("The Kite Runner","Default","4","41.82","Yes"),
("The Girl on the Train","Default","2","55.02","Yes"),
("The Emerald Mystery","Default","2","23.15","Yes"),
("The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.","Default","3","32.00","Yes"),
("The Art of War","Default","5","33.34","Yes"),
("Secrets and Lace (Fatal Hearts #1)","Default","1","20.27","Yes"),
("Romero and Juliet: A Tragic Tale of Love and Zombies","Default","1","36.94","Yes"),
("Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form","Default","1","41.06","Yes"),
("Miss Peregrineâ's Home for Peculiar Children (Miss Peregrineâ's Peculiar Children #1)","Default","1","10.76","Yes"),
("Large Print Heart of the Pride","Default","2","19.15","Yes"),
("Grumbles","Default","2","22.16","Yes"),
("First Steps for New Christians (Print Edition)","Default","1","29.00","Yes"),
("Eureka Trivia 6.0","Default","4","54.59","Yes"),
("Drive: The Surprising Truth About What Motivates Us","Default","4","34.95","Yes"),
("Done Rubbed Out (Reightman & Bailey #1)","Default","5","37.72","Yes"),
("Beauty Restored (Riley Family Legacy Novellas #3)","Default","2","11.11","Yes"),
("Ayumi's Violin","Default","2","15.48","Yes"),
("Anonymous","Default","4","46.82","Yes"),
("Amy Meets the Saints and Sages","Default","3","18.46","Yes"),
("Amatus","Default","5","50.54","Yes"),
("V for Vendetta (V for Vendetta Complete)","Default","4","37.10","Yes"),
("Unbroken: A World War II Story of Survival, Resilience, and Redemption","Default","2","45.95","Yes"),
("The Wright Brothers","Default","4","56.80","Yes"),
("The Songs of the Gods","Default","5","44.48","Yes"),
("The Rosie Project (Don Tillman #1)","Default","1","54.04","Yes"),
("The Power of Habit: Why We Do What We Do in Life and Business","Default","3","16.88","Yes"),
("Steve Jobs","Default","5","39.50","Yes"),
("Luckiest Girl Alive","Default","3","49.83","Yes"),
("Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments","Default","4","46.91","Yes"),
("Lady Midnight (The Dark Artifices #1)","Default","5","16.28","Yes"),
("Hush, Hush (Hush, Hush #1)","Default","3","47.02","Yes"),
("Greek Mythic History","Default","5","10.23","Yes"),
("Every Last Word","Default","3","46.47","Yes"),
("Daily Fantasy Sports","Default","1","36.58","Yes"),
("Clockwork Angel (The Infernal Devices #1)","Default","1","44.14","Yes"),
("City of Fallen Angels (The Mortal Instruments #4)","Default","4","11.23","Yes"),
("City of Bones (The Mortal Instruments #1)","Default","1","43.28","Yes"),
("City of Ashes (The Mortal Instruments #2)","Default","1","47.27","Yes"),
("Carry On, Warrior: Thoughts on Life Unarmed","Default","3","31.85","Yes"),
("Carrie","Default","2","46.23","Yes"),
("Angels & Demons (Robert Langdon #1)","Default","3","51.48","Yes"),
("The Three Searches, Meaning, and the Story","Default","3","13.33","Yes"),
("Raspberry Pi Electronics Projects for the Evil Genius","Default","4","49.67","Yes"),
("How to Speak Golf: An Illustrated Guide to Links Lingo","Default","5","58.32","Yes"),
("Eleanor & Park","Default","5","56.51","Yes"),
("Troublemaker: Surviving Hollywood and Scientology","Default","2","48.39","Yes"),
("Adultery","Default","5","20.88","Yes"),
("Unlimited Intuition Now","Default","4","58.87","Yes"),
("Underlying Notes","Default","2","11.82","Yes"),
("The New Brand You: Your New Image Makes the Sale for You","Default","5","44.05","Yes"),
("The Flowers Lied","Default","2","16.68","Yes"),
("NaNo What Now? Finding your editing process, revising your NaNoWriMo book and building a writing career through publishing and beyond","Default","4","10.41","Yes"),
("Modern Day Fables","Default","2","47.44","Yes"),
("The Unlikely Pilgrimage of Harold Fry (Harold Fry #1)","Default","5","43.62","Yes"),
("The Martian (The Martian #1)","Default","2","41.39","Yes"),
("Left Behind (Left Behind #1)","Default","2","40.72","Yes"),
("John Vassos: Industrial Design for Modern Life","Default","4","20.22","Yes"),
("I'll Give You the Sun","Default","1","56.48","Yes"),
("Heaven is for Real: A Little Boy's Astounding Story of His Trip to Heaven and Back","Default","2","52.86","Yes"),
("Ender's Game (The Ender Quintet #1)","Default","1","43.64","Yes"),
("Death by Leisure: A Cautionary Tale","Default","4","37.51","Yes"),
("Wildlife of New York: A Five-Borough Coloring Book","Default","2","22.14","Yes"),
("The Year of Living Biblically: One Man's Humble Quest to Follow the Bible as Literally as Possible","Default","1","34.72","Yes"),
("The Great Gatsby","Default","4","36.05","Yes"),
("The Good Girl","Default","3","49.03","Yes"),
("The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change","Default","4","33.17","Yes"),
("Steal Like an Artist: 10 Things Nobody Told You About Being Creative","Default","2","20.90","Yes"),
("Life of Pi","Default","4","13.22","Yes"),
("The Sound Of Love","Default","5","57.84","Yes"),
("The Perks of Being a Wallflower","Default","3","55.02","Yes"),
("The Makings of a Fatherless Child","Default","2","31.58","Yes"),
("The Hobbit (Middle-Earth Universe)","Default","5","17.80","Yes"),
("The Fellowship of the Ring (The Lord of the Rings #1)","Default","2","10.27","Yes"),
("Ship Leaves Harbor: Essays on Travel by a Recovering Journeyman","Default","3","30.60","Yes"),
("Musicophilia: Tales of Music and the Brain","Default","1","46.58","Yes"),
("What If?: Serious Scientific Answers to Absurd Hypothetical Questions","Default","4","53.68","Yes"),
("The Fault in Our Stars","Default","1","47.22","Yes"),
("The Dream Thieves (The Raven Cycle #2)","Default","1","34.50","Yes"),
("The 5th Wave (The 5th Wave #1)","Default","2","11.83","Yes"),
("Shiver (The Wolves of Mercy Falls #1)","Default","5","16.23","Yes"),
("Remember Me?","Default","3","11.48","Yes"),
("If I Stay (If I Stay #1)","Default","5","38.13","Yes"),
("I Know Why the Caged Bird Sings (Maya Angelou's Autobiography #1)","Default","2","36.55","Yes"),
("Harry Potter and the Deathly Hallows (Harry Potter #7)","Default","1","23.32","Yes"),
("Fool Me Once","Default","1","16.96","Yes"),
("Drama","Default","2","38.70","Yes"),
("Blue Lily, Lily Blue (The Raven Cycle #3)","Default","5","34.13","Yes"),
("Alight (The Generations Trilogy #2)","Default","4","58.59","Yes"),
("Vogue Colors A to Z: A Fashion Coloring Book","Default","4","52.35","Yes"),
("The Shining (The Shining #1)","Default","3","27.88","Yes"),
("The Hunger Games (The Hunger Games #1)","Default","5","29.85","Yes"),
("Outlander (Outlander #1)","Default","5","19.67","Yes"),
("Mockingjay (The Hunger Games #3)","Default","4","20.44","Yes"),
("Harry Potter and the Sorcerer's Stone (Harry Potter #1)","Default","3","13.90","Yes"),
("Confessions of a Shopaholic (Shopaholic #1)","Default","2","48.94","Yes"),
("Zero History (Blue Ant #3)","Default","1","34.77","Yes"),
("World War Z: An Oral History of the Zombie War","Default","1","21.80","Yes"),
("Wild: From Lost to Found on the Pacific Crest Trail","Default","3","46.02","Yes"),
("Where'd You Go, Bernadette","Default","1","18.13","Yes"),
("Twilight (Twilight #1)","Default","2","41.93","Yes"),
("The Paris Wife","Default","3","36.80","Yes"),
("The Maze Runner (The Maze Runner #1)","Default","1","20.93","Yes"),
("The Lover's Dictionary","Default","2","58.09","Yes"),
("The Goldfinch","Default","3","43.58","Yes"),
("The Giver (The Giver Quartet #1)","Default","1","12.30","Yes"),
("The Girl Who Played with Fire (Millennium Trilogy #2)","Default","2","22.14","Yes"),
("The Demon-Haunted World: Science as a Candle in the Dark","Default","4","52.25","Yes"),
("The Book Thief","Default","2","53.49","Yes"),
("The Autobiography of Malcolm X","Default","2","23.43","Yes"),
("Shopaholic & Baby (Shopaholic #5)","Default","2","46.45","Yes"),
("Quiet: The Power of Introverts in a World That Can't Stop Talking","Default","1","43.55","Yes"),
("Packing for Mars: The Curious Science of Life in the Void","Default","2","56.68","Yes"),
("Orange Is the New Black","Default","2","24.61","Yes"),
("One for the Money (Stephanie Plum #1)","Default","2","32.87","Yes"),
("Morning Star (Red Rising #3)","Default","1","29.40","Yes"),
("Life After Life","Default","2","26.13","Yes"),
("Lean In: Women, Work, and the Will to Lead","Default","1","25.02","Yes"),
("Is Everyone Hanging Out Without Me? (And Other Concerns)","Default","3","20.11","Yes"),
("Gone Girl","Default","5","37.60","Yes"),
("Fellside","Default","1","38.62","Yes"),
("Eclipse (Twilight #3)","Default","1","18.74","Yes"),
("Dracula","Default","3","52.62","Yes"),
("Dead Wake: The Last Crossing of the Lusitania","Default","5","39.24","Yes"),
("David and Goliath: Underdogs, Misfits, and the Art of Battling Giants","Default","1","17.81","Yes"),
("Dark Places","Default","5","23.90","Yes"),
("Breaking Dawn (Twilight #4)","Default","5","35.28","Yes"),
("Beautiful Creatures (Caster Chronicles #1)","Default","5","21.55","Yes"),
("A Visit from the Goon Squad","Default","5","14.08","Yes"),
("The Zombie Room","Default","5","19.69","Yes"),
("The Name of the Wind (The Kingkiller Chronicle #1)","Default","3","50.59","Yes"),
("Taking Shots (Assassins #1)","Default","2","18.88","Yes"),
("Shatter Me (Shatter Me #1)","Default","1","42.40","Yes"),
("Paradise Lost (Paradise #1)","Default","1","24.96","Yes"),
("On the Road (Duluoz Legend)","Default","3","32.36","Yes"),
("Jane Eyre","Default","5","38.43","Yes"),
("Frankenstein","Default","2","38.00","Yes"),
("Mesaerion: The Best Science Fiction Stories 1800-1849","Science Fiction","1","37.59","Yes"),
("Join","Science Fiction","5","35.67","Yes"),
("William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)","Science Fiction","4","43.30","Yes"),
("The Project","Science Fiction","1","10.65","Yes"),
("Soft Apocalypse","Science Fiction","2","26.12","Yes"),
("Sleeping Giants (Themis Files #1)","Science Fiction","1","48.74","Yes"),
("Arena","Science Fiction","4","21.36","Yes"),
("Foundation (Foundation (Publication Order) #1)","Science Fiction","1","32.42","Yes"),
("The Restaurant at the End of the Universe (Hitchhiker's Guide to the Galaxy #2)","Science Fiction","1","10.92","Yes"),
("Ready Player One","Science Fiction","4","19.07","Yes"),
("Life, the Universe and Everything (Hitchhiker's Guide to the Galaxy #3)","Science Fiction","2","33.26","Yes"),
("Dune (Dune #1)","Science Fiction","1","54.86","Yes"),
("Do Androids Dream of Electric Sheep? (Blade Runner #1)","Science Fiction","1","51.48","Yes"),
("Three Wishes (River of Time: California #1)","Science Fiction","2","44.18","Yes"),
("The Last Girl (The Dominion Trilogy #1)","Science Fiction","2","36.26","Yes"),
("Having the Barbarian's Baby (Ice Planet Barbarians #7.5)","Science Fiction","4","34.96","Yes"),
("The Book of Basketball: The NBA According to The Sports Guy","Sports and Games","5","44.84","Yes"),
("Friday Night Lights: A Town, a Team, and a Dream","Sports and Games","3","51.22","Yes"),
("Sugar Rush (Offensive Line #2)","Sports and Games","1","24.42","Yes"),
("Settling the Score (The Summer Games #1)","Sports and Games","2","44.91","Yes"),
("Icing (Aces Hockey #2)","Sports and Games","4","40.44","Yes"),
("The Torch Is Passed: A Harding Family Story","Add a comment","1","19.09","Yes"),
("The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy","Add a comment","4","23.89","Yes"),
("The Art Forger","Add a comment","3","40.76","Yes"),
("On a Midnight Clear","Add a comment","3","14.07","Yes"),
("Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)","Add a comment","2","53.90","Yes"),
("Shobu Samurai, Project Aryoku (#3)","Add a comment","3","29.06","Yes"),
("Modern Romance","Add a comment","5","28.26","Yes"),
("The White Queen (The Cousins' War #1)","Add a comment","5","25.91","Yes"),
("The Song of Achilles","Add a comment","5","37.40","Yes"),
("The Immortal Life of Henrietta Lacks","Add a comment","2","40.67","Yes"),
("The Dovekeepers","Add a comment","1","48.78","Yes"),
("More Than Music (Chasing the Dream #1)","Add a comment","2","37.61","Yes"),
("Code Name Verity (Code Name Verity #1)","Add a comment","4","22.13","Yes"),
("Cell","Add a comment","4","20.29","Yes"),
("Angels Walking (Angels Walking #1)","Add a comment","2","34.20","Yes"),
("A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer","Add a comment","2","56.48","Yes"),
("A People's History of the United States","Add a comment","2","40.79","Yes"),
("A Brush of Wings (Angels Walking #3)","Add a comment","1","55.51","Yes"),
("Rook","Add a comment","4","37.86","Yes"),
("The Midnight Watch: A Novel of the Titanic and the Californian","Add a comment","1","26.20","Yes"),
("The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore","Add a comment","4","59.15","Yes"),
("The Children","Add a comment","3","11.88","Yes"),
("One with You (Crossfire #5)","Add a comment","4","15.71","Yes"),
("Without Shame","Add a comment","5","48.27","Yes"),
("Watchmen","Add a comment","4","58.05","Yes"),
("A Hero's Curse (The Unseen Chronicles #1)","Add a comment","3","50.49","Yes"),
("23 Degrees South: A Tropical Tale of Changing Whether...","Add a comment","2","35.79","Yes"),
("The Glass Castle","Add a comment","1","16.24","Yes"),
("The Drowning Girls","Add a comment","3","35.67","Yes"),
("Team of Rivals: The Political Genius of Abraham Lincoln","Add a comment","5","20.12","Yes"),
("John Adams","Add a comment","4","57.43","Yes"),
("Good in Bed (Cannie Shapiro #1)","Add a comment","5","37.05","Yes"),
("The Joy of Cooking","Add a comment","4","43.27","Yes"),
("The Golden Compass (His Dark Materials #1)","Add a comment","1","18.77","Yes"),
("The God Delusion","Add a comment","3","46.85","Yes"),
("Pride and Prejudice","Add a comment","4","19.27","Yes"),
("Mere Christianity","Add a comment","3","48.51","Yes"),
("Fun Home: A Family Tragicomic","Add a comment","4","56.59","Yes"),
("The Raven King (The Raven Cycle #4)","Add a comment","2","30.57","Yes"),
("Find Her (Detective D.D. Warren #8)","Add a comment","1","22.37","Yes"),
("Evicted: Poverty and Profit in the American City","Add a comment","1","42.27","Yes"),
("A Game of Thrones (A Song of Ice and Fire #1)","Add a comment","2","46.42","Yes"),
("A Clash of Kings (A Song of Ice and Fire #2)","Add a comment","3","10.79","Yes"),
("The Tipping Point: How Little Things Can Make a Big Difference","Add a comment","2","10.02","Yes"),
("The Rest Is Noise: Listening to the Twentieth Century","Add a comment","1","34.77","Yes"),
("The Purpose Driven Life: What on Earth Am I Here for?","Add a comment","3","37.19","Yes"),
("The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy #1)","Add a comment","3","47.80","Yes"),
("The Girl Who Kicked the Hornet's Nest (Millennium Trilogy #3)","Add a comment","1","57.48","Yes"),
("The End of Faith: Religion, Terror, and the Future of Reason","Add a comment","4","22.13","Yes"),
("The Complete Poems","Add a comment","5","41.32","Yes"),
("The Catcher in the Rye","Add a comment","1","24.55","Yes"),
("The Case for Christ (Cases for Christianity)","Add a comment","1","47.84","Yes"),
("The Blind Side: Evolution of a Game","Add a comment","5","53.71","Yes"),
("Seven Days in the Art World","Add a comment","2","52.33","Yes"),
("Sarah's Key","Add a comment","1","46.29","Yes"),
("Rogue Lawyer (Rogue Lawyer #1)","Add a comment","3","50.11","Yes"),
("Manuscript Found in Accra","Add a comment","2","34.98","Yes"),
("Fire Bound (Sea Haven/Sisters of the Heart #5)","Add a comment","4","21.28","Yes"),
("Cosmos","Add a comment","2","36.17","Yes"),
("#GIRLBOSS","Add a comment","1","50.96","Yes"),
("The Sense of an Ending","Add a comment","3","31.38","Yes"),
("The Republic","Add a comment","3","33.78","Yes"),
("The Odyssey","Add a comment","3","29.64","Yes"),
("The Light of the Fireflies","Add a comment","1","54.43","Yes"),
("The Iliad","Add a comment","1","16.16","Yes"),
("The Communist Manifesto","Add a comment","3","14.76","Yes"),
("Lord of the Flies","Add a comment","3","24.89","Yes"),
("Unicorn Tracks","Fantasy","3","18.78","Yes"),
("Saga, Volume 6 (Saga (Collected Editions) #6)","Fantasy","3","25.02","Yes"),
("Princess Between Worlds (Wide-Awake Princess #5)","Fantasy","5","13.34","Yes"),
("Masks and Shadows","Fantasy","2","56.40","Yes"),
("Crown of Midnight (Throne of Glass #2)","Fantasy","3","43.29","Yes"),
("Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)","Fantasy","2","28.09","Yes"),
("A Court of Thorns and Roses (A Court of Thorns and Roses #1)","Fantasy","1","52.37","Yes"),
("Throne of Glass (Throne of Glass #1)","Fantasy","3","35.07","Yes"),
("The Glittering Court (The Glittering Court #1)","Fantasy","1","44.28","Yes"),
("Hollow City (Miss Peregrineâ's Peculiar Children #2)","Fantasy","1","42.98","Yes"),
("The Star-Touched Queen","Fantasy","5","46.02","Yes"),
("The Hidden Oracle (The Trials of Apollo #1)","Fantasy","2","52.26","Yes"),
("The Bane Chronicles (The Bane Chronicles #1-11)","Fantasy","4","44.73","Yes"),
("Island of Dragons (Unwanteds #7)","Fantasy","1","29.65","Yes"),
("Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)","Fantasy","5","37.51","Yes"),
("City of Glass (The Mortal Instruments #3)","Fantasy","4","56.02","Yes"),
("Searching for Meaning in Gailana","Fantasy","1","38.73","Yes"),
("The Star-Touched Queen","Fantasy","5","32.30","Yes"),
("A Shard of Ice (The Black Symphony Saga #1)","Fantasy","3","56.63","Yes"),
("King's Folly (The Kinsman Chronicles #1)","Fantasy","5","39.61","Yes"),
("Every Heart a Doorway (Every Heart A Doorway #1)","Fantasy","5","12.16","Yes"),
("A Gathering of Shadows (Shades of Magic #2)","Fantasy","4","44.81","Yes"),
("The Raven Boys (The Raven Cycle #1)","Fantasy","4","57.74","Yes"),
("The False Prince (The Ascendance Trilogy #1)","Fantasy","5","56.00","Yes"),
("Tell the Wind and Fire","Fantasy","3","45.51","Yes"),
("A Feast for Crows (A Song of Ice and Fire #4)","Fantasy","4","17.21","Yes"),
("The Demonists (Demonist #1)","Fantasy","2","52.11","Yes"),
("The Beast (Black Dagger Brotherhood #14)","Fantasy","5","46.08","Yes"),
("Paper and Fire (The Great Library #2)","Fantasy","5","49.45","Yes"),
("Harry Potter and the Order of the Phoenix (Harry Potter #5)","Fantasy","4","31.63","Yes"),
("Harry Potter and the Half-Blood Prince (Harry Potter #6)","Fantasy","5","48.75","Yes"),
("Harry Potter and the Chamber of Secrets (Harry Potter #2)","Fantasy","1","14.74","Yes"),
("The Rose & the Dagger (The Wrath and the Dawn #2)","Fantasy","4","58.64","Yes"),
("Soldier (Talon #3)","Fantasy","2","24.72","Yes"),
("Midnight Riot (Peter Grant/ Rivers of London - books #1)","Fantasy","2","55.46","Yes"),
("Heir to the Sky","Fantasy","4","44.07","Yes"),
("Eragon (The Inheritance Cycle #1)","Fantasy","3","43.87","Yes"),
("Darkfever (Fever #1)","Fantasy","1","56.02","Yes"),
("Ash","Fantasy","4","22.06","Yes"),
("A Storm of Swords (A Song of Ice and Fire #3)","Fantasy","2","31.22","Yes"),
("Vampire Girl (Vampire Girl #1)","Fantasy","2","53.82","Yes"),
("The Silent Twin (Detective Jennifer Knight #3)","Fantasy","3","36.25","Yes"),
("The Mirror & the Maze (The Wrath and the Dawn #1.5)","Fantasy","1","29.38","Yes"),
("Sister Sable (The Mad Queen #1)","Fantasy","3","13.33","Yes"),
("Shadow Rites (Jane Yellowrock #10)","Fantasy","4","21.72","Yes"),
("Origins (Alphas 0.5)","Fantasy","1","28.99","Yes"),
("One Second (Seven #7)","Fantasy","2","52.94","Yes"),
("Myriad (Prentor #1)","Fantasy","4","58.75","Yes"),
("Without Borders (Wanderlove #1)","New Adult","2","45.07","Yes"),
("The Mistake (Off-Campus #2)","New Adult","3","43.29","Yes"),
("The Matchmaker's Playbook (Wingmen Inc. #1)","New Adult","1","55.85","Yes"),
("The Hook Up (Game On #1)","New Adult","5","36.29","Yes"),
("Shameless","New Adult","3","58.35","Yes"),
("Off Sides (Off #1)","New Adult","5","39.45","Yes"),
("The Requiem Red","Young Adult","1","22.65","Yes"),
("Set Me Free","Young Adult","5","17.46","Yes"),
("The Natural History of Us (The Fine Art of Pretending #2)","Young Adult","3","45.22","Yes"),
("Obsidian (Lux #1)","Young Adult","2","14.86","Yes"),
("Burning","Young Adult","3","28.81","Yes"),
("A Fierce and Subtle Poison","Young Adult","4","28.13","Yes"),
("Scarlett Epstein Hates It Here","Young Adult","5","43.55","Yes"),
("Nightingale, Sing","Young Adult","1","38.28","Yes"),
("Library of Souls (Miss Peregrineâ's Peculiar Children #3)","Young Adult","5","48.56","Yes"),
("Frostbite (Vampire Academy #2)","Young Adult","5","29.99","Yes"),
("Wild Swans","Young Adult","2","14.36","Yes"),
("Until Friday Night (The Field Party #1)","Young Adult","2","46.31","Yes"),
("This Is Where It Ends","Young Adult","2","27.12","Yes"),
("The Darkest Lie","Young Adult","5","35.35","Yes"),
("My Kind of Crazy","Young Adult","1","40.36","Yes"),
("Don't Get Caught","Young Adult","1","55.35","Yes"),
("Catching Jordan (Hundred Oaks)","Young Adult","3","50.83","Yes"),
("Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)","Young Adult","4","58.14","Yes"),
("The Epidemic (The Program 0.6)","Young Adult","5","14.44","Yes"),
("Stars Above (The Lunar Chronicles #4.5)","Young Adult","2","48.05","Yes"),
("No Love Allowed (Dodge Cove #1)","Young Adult","4","54.65","Yes"),
("Exit, Pursued by a Bear","Young Adult","4","51.34","Yes"),
("The Alien Club","Young Adult","1","54.40","Yes"),
("Don't Forget Steven","Young Adult","1","33.23","Yes"),
("South of Sunshine","Young Adult","1","28.93","Yes"),
("My Life Next Door (My Life Next Door )","Young Adult","5","36.39","Yes"),
("Future Shock (Future Shock #1)","Young Adult","5","55.65","Yes"),
("Nightstruck: A Novel","Young Adult","4","50.35","Yes"),
("Tell the Wolves I'm Home","Young Adult","2","50.96","Yes"),
("Will Grayson, Will Grayson (Will Grayson, Will Grayson)","Young Adult","4","47.31","Yes"),
("Where She Went (If I Stay #2)","Young Adult","4","41.73","Yes"),
("Two Summers","Young Adult","1","14.64","Yes"),
("The Darkest Corners","Young Adult","5","11.33","Yes"),
("Tell Me Three Things","Young Adult","1","41.81","Yes"),
("Lola and the Boy Next Door (Anna and the French Kiss #2)","Young Adult","4","23.63","Yes"),
("Kill the Boy Band","Young Adult","5","15.52","Yes"),
("Isla and the Happily Ever After (Anna and the French Kiss #3)","Young Adult","5","48.13","Yes"),
("An Abundance of Katherines","Young Adult","5","10.00","Yes"),
("Harry Potter and the Prisoner of Azkaban (Harry Potter #3)","Young Adult","4","24.17","Yes"),
("Walk the Edge (Thunder Road #2)","Young Adult","3","32.36","Yes"),
("Two Boys Kissing","Young Adult","2","32.74","Yes"),
("The New Guy (and Other Senior Year Distractions)","Young Adult","3","44.92","Yes"),
("The Land of 10,000 Madonnas","Young Adult","4","29.64","Yes"),
("Scarlet (The Lunar Chronicles #2)","Young Adult","4","14.57","Yes"),
("Legend (Legend #1)","Young Adult","4","43.69","Yes"),
("Lady Renegades (Rebel Belle #3)","Young Adult","5","53.04","Yes"),
("Golden (Heart of Dread #3)","Young Adult","4","42.21","Yes"),
("Cinder (The Lunar Chronicles #1)","Young Adult","1","26.09","Yes"),
("Boy Meets Boy","Young Adult","3","21.12","Yes"),
("Annie on My Mind","Young Adult","5","36.83","Yes"),
("New Moon (Twilight #2)","Young Adult","4","12.86","Yes"),
("Girl Online On Tour (Girl Online #2)","Young Adult","1","53.47","Yes"),
("The Haters","Young Adult","5","27.89","Yes"),
("The Art of Not Breathing","Young Adult","4","40.83","Yes"),
("The Most Perfect Thing: Inside (and Outside) a Bird's Egg","Science","4","42.96","Yes"),
("Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine","Science","5","57.36","Yes"),
("Sorting the Beef from the Bull: The Science of Food Fraud Forensics","Science","4","44.74","Yes"),
("Tipping Point for Planet Earth: How Close Are We to the Edge?","Science","1","37.55","Yes"),
("The Fabric of the Cosmos: Space, Time, and the Texture of Reality","Science","1","55.91","Yes"),
("Diary of a Citizen Scientist: Chasing Tiger Beetles and Other New Ways of Engaging the World","Science","1","28.41","Yes"),
("The Origin of Species","Science","4","10.01","Yes"),
("The Grand Design","Science","3","13.76","Yes"),
("Peak: Secrets from the New Science of Expertise","Science","2","16.28","Yes"),
("The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory","Science","4","13.03","Yes"),
("The Disappearing Spoon: And Other True Tales of Madness, Love, and the History of the World from the Periodic Table of the Elements","Science","5","57.35","Yes"),
("Surely You're Joking, Mr. Feynman!: Adventures of a Curious Character","Science","2","25.83","Yes"),
("Seven Brief Lessons on Physics","Science","4","30.60","Yes"),
("The Selfish Gene","Science","1","29.45","Yes"),
("A Light in the Attic","Poetry","3","51.77","Yes"),
("The Black Maria","Poetry","1","52.15","Yes"),
("Shakespeare's Sonnets","Poetry","4","20.66","Yes"),
("Olio","Poetry","1","23.88","Yes"),
("You can't bury them all: Poems","Poetry","2","33.63","Yes"),
("Slow States of Collapse: Poems","Poetry","3","57.31","Yes"),
("Untitled Collection: Sabbath Poems 2014","Poetry","4","14.27","Yes"),
("Poems That Make Grown Women Cry","Poetry","4","14.19","Yes"),
("Night Sky with Exit Wounds","Poetry","1","41.05","Yes"),
("salt.","Poetry","4","46.78","Yes"),
("Quarter Life Poetry: Poems for the Young, Broke and Hangry","Poetry","5","50.89","Yes"),
("Out of Print: City Lights Spotlight No. 14","Poetry","5","53.64","Yes"),
("Les Fleurs du Mal","Poetry","5","29.04","Yes"),
("Howl and Other Poems","Poetry","2","40.45","Yes"),
("Leave This Song Behind: Teen Poetry at Its Best","Poetry","5","51.17","Yes"),
("The Collected Poems of W.B. Yeats (The Collected Works of W.B. Yeats #1)","Poetry","5","15.42","Yes"),
("The Crossover","Poetry","4","38.77","Yes"),
("Booked","Poetry","5","17.49","Yes"),
("Twenty Love Poems and a Song of Despair","Poetry","4","30.95","Yes"),
("Vampire Knight, Vol. 1 (Vampire Knight #1)","Paranormal","1","15.40","Yes"),
("Wall and Piece","Art","4","44.18","Yes"),
("Feathers: Displays of Brilliant Plumage","Art","3","49.05","Yes"),
("Art and Fear: Observations on the Perils (and Rewards) of Artmaking","Art","4","48.63","Yes"),
("The New Drawing on the Right Side of the Brain","Art","3","43.02","Yes"),
("History of Beauty","Art","4","10.29","Yes"),
("The Story of Art","Art","4","41.14","Yes"),
("The Art Book","Art","2","32.34","Yes"),
("Ways of Seeing","Art","5","39.51","Yes"),
("The Lucifer Effect: Understanding How Good People Turn Evil","Psychology","1","10.40","Yes"),
("The Golden Condom: And Other Essays on Love Lost and Found","Psychology","1","39.43","Yes"),
("It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle","Psychology","3","56.27","Yes"),
("An Unquiet Mind: A Memoir of Moods and Madness","Psychology","3","21.30","Yes"),
("Thinking, Fast and Slow","Psychology","1","21.14","Yes"),
("Civilization and Its Discontents","Psychology","2","59.95","Yes"),
("8 Keys to Mental Health Through Exercise","Psychology","1","31.04","Yes"),
("The Argonauts","Autobiography","2","10.93","Yes"),
("M Train","Autobiography","1","27.18","Yes"),
("Lab Girl","Autobiography","1","40.85","Yes"),
("Approval Junkie: Adventures in Caring Too Much","Autobiography","5","58.81","Yes"),
("Running with Scissors","Autobiography","4","12.91","Yes"),
("Me Talk Pretty One Day","Autobiography","2","57.60","Yes"),
("Lust & Wonder","Autobiography","2","11.87","Yes"),
("Life Without a Recipe","Autobiography","5","59.04","Yes"),
("A Heartbreaking Work of Staggering Genius","Autobiography","5","54.29","Yes"),
("Catastrophic Happiness: Finding Joy in Childhood's Messy Years","Parenting","2","37.35","Yes"),
("Fifty Shades Freed (Fifty Shades #3)","Adult Fiction","5","15.36","Yes"),
("The Long Haul (Diary of a Wimpy Kid #9)","Humor","1","44.07","Yes"),
("Old School (Diary of a Wimpy Kid #10)","Humor","5","11.83","Yes"),
("I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction","Humor","4","25.98","Yes"),
("Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened","Humor","5","14.75","Yes"),
("Dress Your Family in Corduroy and Denim","Humor","3","43.68","Yes"),
("Toddlers Are A**holes: It's Not Your Fault","Humor","1","25.55","Yes"),
("When You Are Engulfed in Flames","Humor","5","30.89","Yes"),
("Naked","Humor","3","31.69","Yes"),
("Lamb: The Gospel According to Biff, Christ's Childhood Pal","Humor","5","55.50","Yes"),
("Holidays on Ice","Humor","2","51.07","Yes"),
("Security","Horror","2","39.25","Yes"),
("Follow You Home","Horror","1","21.36","Yes"),
("The Loney","Horror","1","23.40","Yes"),
("Pet Sematary","Horror","3","10.56","Yes"),
("Doctor Sleep (The Shining #2)","Horror","2","40.12","Yes"),
("Psycho: Sanitarium (Psycho #1.5)","Horror","5","36.97","Yes"),
("Can You Keep a Secret? (Fear Street Relaunch #4)","Horror","1","48.64","Yes"),
("Red Dragon (Hannibal Lecter #1)","Horror","3","23.37","Yes"),
("Dracula the Un-Dead","Horror","5","35.63","Yes"),
("Night Shift (Night Shift #1-20)","Horror","4","12.75","Yes"),
("Needful Things","Horror","4","47.51","Yes"),
("Misery","Horror","2","34.79","Yes"),
("It","Horror","3","25.01","Yes"),
("'Salem's Lot","Horror","4","49.56","Yes"),
("The Stand","Horror","2","57.86","Yes"),
("The Girl with All the Gifts","Horror","3","49.47","Yes"),
("House of Leaves","Horror","1","54.89","Yes"),
("Sapiens: A Brief History of Humankind","History","5","54.23","Yes"),
("Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink","History","1","25.52","Yes"),
("The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind","History","1","19.73","Yes"),
("Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics","History","2","36.28","Yes"),
("Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History","History","1","59.64","Yes"),
("Zealot: The Life and Times of Jesus of Nazareth","History","3","24.70","Yes"),
("A Distant Mirror: The Calamitous 14th Century","History","3","14.58","Yes"),
("1491: New Revelations of the Americas Before Columbus","History","3","21.80","Yes"),
("Brilliant Beacons: A History of the American Lighthouse","History","3","11.45","Yes"),
("'Most Blessed of the Patriarchs': Thomas Jefferson and the Empire of the Imagination","History","5","44.48","Yes"),
("A Short History of Nearly Everything","History","5","52.40","Yes"),
("The Rise and Fall of the Third Reich: A History of Nazi Germany","History","2","39.67","Yes"),
("Catherine the Great: Portrait of a Woman","History","4","58.55","Yes"),
("The Mathews Men: Seven Brothers and the War Against Hitler's U-boats","History","5","42.91","Yes"),
("The Hiding Place","History","4","55.91","Yes"),
("America's War for the Greater Middle East: A Military History","History","2","51.22","Yes"),
("The Guns of August","History","2","14.54","Yes"),
("House of Lost Worlds: Dinosaurs, Dynasties, and the Story of Life on Earth","History","2","43.70","Yes"),
("Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More","Food and Drink","3","30.52","Yes"),
("The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!","Food and Drink","1","56.41","Yes"),
("My Paris Kitchen: Recipes and Stories","Food and Drink","2","33.37","Yes"),
("Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed","Food and Drink","4","14.02","Yes"),
("Layered: Baking, Building, and Styling Spectacular Cakes","Food and Drink","1","40.11","Yes"),
("The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us","Food and Drink","5","37.34","Yes"),
("The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking","Food and Drink","2","37.60","Yes"),
("The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First","Food and Drink","1","41.25","Yes"),
("Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals","Food and Drink","3","42.16","Yes"),
("The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth","Food and Drink","3","28.77","Yes"),
("It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes","Food and Drink","1","19.55","Yes"),
("Barefoot Contessa Back to Basics","Food and Drink","1","28.01","Yes"),
("Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again","Food and Drink","5","50.62","Yes"),
("My Kitchen Year: 136 Recipes That Saved My Life","Food and Drink","2","11.53","Yes"),
("Everyday Italian: 125 Simple and Delicious Recipes","Food and Drink","5","20.10","Yes"),
("A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More","Food and Drink","1","38.77","Yes"),
("Cravings: Recipes for What You Want to Eat","Food and Drink","3","20.50","Yes"),
("The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York","Food and Drink","4","12.34","Yes"),
("32 Yolks","Food and Drink","2","53.63","Yes"),
("Naturally Lean: 125 Nourishing Gluten-Free, Plant-Based Recipes--All Under 300 Calories","Food and Drink","5","11.38","Yes"),
("How to Cook Everything Vegetarian: Simple Meatless Recipes for Great Food (How to Cook Everything)","Food and Drink","4","46.01","Yes"),
("How to Be a Domestic Goddess: Baking and the Art of Comfort Cooking","Food and Drink","2","28.25","Yes"),
("The Barefoot Contessa Cookbook","Food and Drink","5","59.92","Yes"),
("Better Homes and Gardens New Cook Book","Food and Drink","3","39.61","Yes"),
("The Power Greens Cookbook: 140 Delicious Superfood Recipes","Food and Drink","5","11.05","Yes"),
("Mexican Today: New and Rediscovered Recipes for Contemporary Kitchens","Food and Drink","5","24.91","Yes"),
("Vegan Vegetarian Omnivore: Dinner for Everyone at the Table","Food and Drink","2","13.66","Yes"),
("The Smitten Kitchen Cookbook","Food and Drink","1","23.59","Yes"),
("The Art of Simple Food: Notes, Lessons, and Recipes from a Delicious Revolution","Food and Drink","3","34.32","Yes"),
("Hungry Girl Clean & Hungry: Easy All-Natural Recipes for Healthy Eating in the Real World","Food and Drink","3","33.14","Yes"),
("Redeeming Love","Christian Fiction","5","20.47","Yes"),
("Close to You","Christian Fiction","4","49.46","Yes"),
("Shadows of the Past (Logan Point #1)","Christian Fiction","5","39.67","Yes"),
("Like Never Before (Walker Family #2)","Christian Fiction","2","28.77","Yes"),
("Counted With the Stars (Out from Egypt #1)","Christian Fiction","5","17.97","Yes"),
("If I Run (If I Run #1)","Christian Fiction","4","49.97","Yes"),
("The Dirty Little Secrets of Getting Your Dream Job","Business","4","33.34","Yes"),
("The Third Wave: An Entrepreneurâ's Vision of the Future","Business","5","12.61","Yes"),
("The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job","Business","3","27.55","Yes"),
("Shoe Dog: A Memoir by the Creator of NIKE","Business","2","23.99","Yes"),
("Made to Stick: Why Some Ideas Survive and Others Die","Business","5","38.85","Yes"),
("Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two","Business","1","43.14","Yes"),
("The Art of Startup Fundraising","Business","3","21.00","Yes"),
("Born for This: How to Find the Work You Were Meant to Do","Business","5","21.59","Yes"),
("The E-Myth Revisited: Why Most Small Businesses Don't Work and What to Do About It","Business","1","36.91","Yes"),
("Rich Dad, Poor Dad","Business","1","51.74","Yes"),
("The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses","Business","3","33.92","Yes"),
("Rework","Business","2","44.88","Yes"),
("Louisa: The Extraordinary Life of Mrs. Adams","Biography","2","16.85","Yes"),
("Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena","Biography","2","21.15","Yes"),
("The Faith of Christopher Hitchens: The Restless Soul of the World's Most Notorious Atheist","Biography","1","39.55","Yes"),
("Benjamin Franklin: An American Life","Biography","3","48.19","Yes"),
("The Rise of Theodore Roosevelt (Theodore Roosevelt #1)","Biography","3","42.57","Yes"),
("In Her Wake","Thriller","1","12.84","Yes"),
("The Elephant Tree","Thriller","5","23.82","Yes"),
("Behind Closed Doors","Thriller","4","52.22","Yes"),
("You (You #1)","Thriller","5","43.61","Yes"),
("The Guilty (Will Robie #4)","Thriller","2","13.82","Yes"),
("The 14th Colony (Cotton Malone #11)","Thriller","1","39.24","Yes"),
("Give It Back","Thriller","2","18.32","Yes"),
("Killing Floor (Jack Reacher #1)","Thriller","4","31.49","Yes"),
("The Bone Hunters (Lexy Vaughan & Steven Macaulay #2)","Thriller","3","59.71","Yes"),
("Far From True (Promise Falls Trilogy #2)","Thriller","2","34.93","Yes"),
("The Travelers","Thriller","1","15.77","Yes"),
("When We Collided","Contemporary","1","31.77","Yes"),
("Someone Like You (The Harrisons #2)","Contemporary","5","52.79","Yes"),
("We Are All Completely Beside Ourselves","Contemporary","1","24.04","Yes"),
("The Four Agreements: A Practical Guide to Personal Freedom","Spirituality","5","17.66","Yes"),
("The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution","Spirituality","5","32.24","Yes"),
("Chasing Heaven: What Dying Taught Me About Living","Spirituality","2","37.80","Yes"),
("If I Gave You God's Phone Number....: Searching for Spirituality in America","Spirituality","1","20.91","Yes"),
("Unreasonable Hope: Finding Faith in the God Who Brings Purpose to Your Pain","Spirituality","2","46.33","Yes"),
("A New Earth: Awakening to Your Life's Purpose","Spirituality","5","55.65","Yes"),
("Logan Kade (Fallen Crest High #5.5)","Academic","2","13.12","Yes"),
("Online Marketing for Busy Authors: A Step-By-Step Guide","Self Help","1","46.35","Yes"),
("How to Be Miserable: 40 Strategies You Already Use","Self Help","1","46.03","Yes"),
("Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress","Self Help","3","52.15","Yes"),
("You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life","Self Help","3","12.08","Yes"),
("How to Stop Worrying and Start Living","Self Help","5","46.49","Yes"),
("All the Light We Cannot See","Historical","5","29.87","Yes"),
("The Girl You Left Behind (The Girl You Left Behind #1)","Historical","1","15.79","Yes"),
("(Un)Qualified: How God Uses Broken People to Do Big Things","Christian","5","54.00","Yes"),
("Crazy Love: Overwhelmed by a Relentless God","Christian","2","47.72","Yes"),
("Blue Like Jazz: Nonreligious Thoughts on Christian Spirituality","Christian","1","25.77","Yes"),
("Silence in the Dark (Logan Point #4)","Suspense","3","58.33","Yes"),
("The Grownup","Short Stories","1","35.88","Yes"),
("Suzie Snowflake: One beautiful flake (a self-esteem story)","Novels","5","54.81","Yes"),
("The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life","Health","3","49.05","Yes"),
("Eat Fat, Get Thin","Health","2","54.07","Yes"),
("10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!","Health","5","49.71","Yes"),
("The Art and Science of Low Carbohydrate Living","Health","5","52.98","Yes"),
("Libertarianism for Beginners","Politics","2","51.33","Yes"),
("Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond","Politics","4","52.65","Yes"),
("Equal Is Unfair: America's Misguided Fight Against Income Inequality","Politics","1","56.86","Yes"),
("Amid the Chaos","Cultural","1","36.58","Yes"),
("Dark Notes","Erotica","5","19.19","Yes"),
("The Long Shadow of Small Ghosts: Murder and Memory in an American City","Crime","1","10.97","Yes");
